image: pmlrsg/gisportal-host

stages:
  - install
  - test

install:
  stage: install
  script:
    - node --version
    - npm --version
    - npm install --silent --depth 0

test:
  stage: test
  script:
    - grunt eslint:check
    - npm test
